<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>asm</string>
		<string>a65</string>
		<string>inc</string>
		<string>def</string>
	</array>
	<key>name</key>
	<string>CA65 6502 Assembler</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.inserted</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\S+):</string>
			<key>name</key>
			<string>comment.function.ca65</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|\s+)\.(?i:bss|code|data|zeropage)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|\s+)\.(?i:a16|a8|addr|align|asciiz|assert|autoimport|byte|byt|case|charmap|condes|constructor|dbyt|debuginfo|defined|define|def|destructor|dword|elseif|else|endenum|endif|endmac|endmacro|endproc|endrep|endrepeat|endscope|endstruct|end|enum|error|exitmacro|exitmac|exportzp|export|faraddr|feature|fileopt|fopt|forceimport|globalzp|global|i16|i8|ifblank|ifconst|ifdef|ifnblank|ifndef|ifnref|ifp02|ifp816|ifpc02|ifpsc02|ifref|if|importzp|import|incbin|include|interruptor|linecont|listbytes|list|localchar|local|macpack|macro|mac|org|out|p02|p816|pagelength|pagelen|pc02|popseg|proc|psc02|pushseg|reloc|repeat|res|rodata|scope|segment|setcpu|smart|struct|sunplus|tag|warning|word|bankbyte|blank|concat|const|hibyte|hiword|ident|left|lobyte|loword|match|mid|ref|referenced|right|sizeof|strat|sprintf|string|strlen|tcount|xmatch|)\b</string>
			<key>name</key>
			<string>keyword.control.command</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.escaped</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.semi-colon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?!\s)\#(?!(^\s))</string>
			<key>name</key>
			<string>storage.immediate</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$)[A-Fa-f0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\%[01]+\b</string>
			<key>name</key>
			<string>constant.numeric.binary</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:bpl|bmi|bvc|bvs|bcc|bcs|bne|beq|jmp|jsr|ret|rti)\b</string>
			<key>name</key>
			<string>markup.inserted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:adc|and|asl|bcc|bcs|beq|bit|bmi|bne|bpl|brk|bvc|bvs|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|jmp|jsr|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|rti|rts|sbc|sec|sed|sei|sta|stx|sty|tax|tay|tsx|txa|txs|tya)\b</string>
			<key>name</key>
			<string>support.function.mnemonic.ca65</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[^\.][a-zA-Z_][a-zA-Z_0-9]*\b</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\+\-\*\/]</string>
			<key>name</key>
			<string>operator</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm6502</string>
	<key>uuid</key>
	<string>c43df48f-a6ca-46cb-989d-ccb487838d57</string>
</dict>
</plist>
